import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Card from "@/componentes/Card/Card";
import Topo from "@/componentes/Topo/Topo";
import Rodape from "@/componentes/Rodape/Rodape";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

       <Topo/>
      <section className={styles.section}> 
        <Card/>
        <Card/>
        <Card/>
      </section>
      <Rodape/>
    </>
  );
}
