import "./globals.css";
import Topo from "@/componentes/topo/Topo";



export const metadata = {
  title: "Gelateria - Sorveteria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Topo />
        {children}
      </body>
    </html>
  );
}
