import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Topo from "@/componentes/topo";
import SecaoCapa from "@/componentes/secao-capa";
import SecaoProdutos from "@/componentes/secao-produtos";
import SecaoSobre from "@/componentes/secao-sobre";
import SecaoContato from "@/componentes/secao-contato";
import Rodape from "@/componentes/rodape";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Topo/>
        <SecaoCapa/>
        <SecaoProdutos/>
        <SecaoSobre/>
        <SecaoContato/>
        <Rodape/>
      </main>
    </>
  );
}
